plugin:
  name: custom-data-type-ubhdgnd
  version: 1.2
  url: https://gitlab.ub.uni-heidelberg.de/kba/easydb-custom-data-type-ubhdgnd
  displayname:
    de-DE: GND Plugin UB Heidelberg
    en-US: GND Plugin UB Heidelberg
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-ubhdgnd.js
    l10n: l10n/
    css: custom-data-type-ubhdgnd.css
custom_types:
  ubhdgnd:
    update:
      script: build/scripts/ubhdgnd-update.js
      timeout: 60
      batch_size: 100
      interval_base_config: update_interval_gnd.days
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text_oneline
      conceptSeeAlso:
        type: text
    config:
      schema:
        - name: 'search'
          parameters:
            authorities_backend:
              type: 'select'
              options:
                - 'ubhd/gnd'
                - 'gbv/gnd'
              position: 1
            gnd_types:
              position: 2
              # We have to use type: text (or int), because the current logic does not take 'plugin_type' in to account for 'string-list'
              # See BaseConfig.getFieldDefFromParm
              type: text
              plugin_type: options-tree
              choices:
                - 'PlaceOrGeographicName'
                - '    AdministrativeUnit'
                - '    BuildingOrMemorial'
                - '    Country'
                - '    ExtraterrestrialTerritory'
                - '    FictivePlace'
                - '    MemberState'
                - '    NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit'
                - '    NaturalGeographicUnit'
                - '    ReligiousTerritory'
                - '    TerritorialCorporateBodyOrAdministrativeUnit'
                - '    WayBorderOrLine'
                - 'Person'
                - '    DifferentiatedPerson'
                - '        CollectivePseudonym'
                - '        Gods'
                - '        LiteraryOrLegendaryCharacter'
                - '        Pseudonym'
                - '        RoyalOrMemberOfARoyalHouse'
                - '        Spirits'
                - '    UndifferentiatedPerson'
                - 'Family'
                - 'ConferenceOrEvent'
                - '    SeriesOfConferenceOrEvent'
                - 'CorporateBody'
                - '    Company'
                - '    MusicalCorporateBody'
                - '    FictiveCorporateBody'
                - '    OrganOfCorporateBody'
                - '    ProjectOrProgram'
                - '    ReligiousAdministrativeUnit'
                - '    ReligiousCorporateBody'
                - 'SubjectHeading'
                - '    CharactersOrMorphemes'
                - '    EthnographicName'
                - '    FictiveTerm'
                - '    GroupOfPersons'
                - '    HistoricSingleEventOrEra'
                - '    Language'
                - '    MeansOfTransportWithIndividualName'
                - '    NomenclatureInBiologyOrChemistry'
                - '    ProductNameOrBrandName'
                - '    SoftwareProduct'
                - '    SubjectHeadingSensoStricto'
                - 'Work'
                - '    Collection'
                - '    CollectiveManuscript'
                - '    Expression'
                - '    Manuscript'
                - '    MusicalWork'
                - '    ProvenanceCharacteristic'
                - '    VersionOfAMusicalWork'
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool

